# Generated by Django 4.1.7 on 2023-06-11 07:07

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('subject', models.CharField(choices=[('phone', 'تلفن همراه'), ('email', 'ایمیل')], max_length=20, verbose_name='نوع کد تایید')),
                ('code', models.CharField(blank=True, default=accounts.utils.generate_new_verification_code, editable=False, max_length=10, unique=True, verbose_name='کد تایید')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'نامعتبر'), (1, 'معتبر'), (2, 'اعمال شده')], default=1, verbose_name='وضعیت کد')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کدهای تایید',
            },
        ),
    ]
