# Generated by Django 4.1.7 on 2023-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveData',
            fields=[
                ('post_id', models.FloatField(primary_key=True, serialize=False)),
                ('field_billing_country', models.TextField(blank=True, db_collation='utf8mb4_persian_ci', db_column='_billing_country', null=True)),
                ('field_billing_first_name', models.TextField(blank=True, db_collation='utf8mb4_unicode_520_ci', db_column='_billing_first_name', null=True)),
                ('field_billing_last_name', models.TextField(blank=True, db_collation='utf8mb4_unicode_520_ci', db_column='_billing_last_name', null=True)),
                ('field_billing_phone', models.TextField(blank=True, db_collation='utf8mb4_unicode_520_ci', db_column='_billing_phone', null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('qty_extra', models.FloatField()),
            ],
            options={
                'db_table': 'Reserve_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpHotelBookingOrderItemmeta',
            fields=[
                ('meta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotel_booking_order_item_id', models.PositiveBigIntegerField()),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_hotel_booking_order_itemmeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpPostmeta',
            fields=[
                ('meta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_id', models.PositiveBigIntegerField()),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wp_postmeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WpPosts',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('post_author', models.PositiveBigIntegerField()),
                ('post_date', models.DateTimeField()),
                ('post_date_gmt', models.DateTimeField()),
                ('post_content', models.TextField()),
                ('post_title', models.TextField()),
                ('post_excerpt', models.TextField()),
                ('post_status', models.CharField(max_length=20)),
                ('comment_status', models.CharField(max_length=20)),
                ('ping_status', models.CharField(max_length=20)),
                ('post_password', models.CharField(max_length=255)),
                ('post_name', models.CharField(max_length=200)),
                ('to_ping', models.TextField()),
                ('pinged', models.TextField()),
                ('post_modified', models.DateTimeField()),
                ('post_modified_gmt', models.DateTimeField()),
                ('post_content_filtered', models.TextField()),
                ('post_parent', models.PositiveBigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('menu_order', models.IntegerField()),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(max_length=100)),
                ('comment_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'wp_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReseveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('post_id', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
